// list from https://archive.izmostock.com/gallery-list

const brandsCollection = [
    'Acura',
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Audi',
    'Bentley',
    'BMW',
    'BMW',
    'Chevrolet',
    'Chevrolet',
    'Citroen',
    'Citroen',
    'Cupra',
    'Dodge',
    'Ferrari',
    'Fiat',
    'Fiat',
    'Ford',
    'Ford',
    'Ford',
    'Genesis',
    'Honda',
    'Hyundai',
    'Infiniti',
    'Jaguar',
    'Jeep',
    'Kia',
    'Kia',
    'Lexus',
    'Lincoln',
    'Maserati',
    'Mazda',
    'Mazda',
    'Mercedes',
    'Mercedes',
    'Mitsubishi',
    'Nissan',
    'Opel',
    'Opel',
    'Peugeot',
    'Peugeot',
    'Porsche',
    'Renault',
    'Skoda',
    'Subaru',
    'Suzuki',
    'Toyota',
    'Toyota',
    'Toyota',
    'Volkswagen',
    'Volkswagen',
    'Volvo',
    'Volvo',
    'LADA',
    'LADA',
    'LADA',
];

export default brandsCollection;
