const modelCollection = [
    'RLX',
    'Mito',
    'DBX',
    'A6 Quattro',
    'Q3 Sport',
    'Continental',
    '5 Sport Gran',
    '7 xDrive',
    'Camaro',
    'Impala',
    'C5',
    'C4 Grand',
    'Formentor',
    'Challenger',
    'Portofino',
    'Lounge Mini',
    'Panda Cross',
    'C-Max',
    'Explorer',
    'Mustang',
    'GV80',
    'Civic DX',
    'Elantra',
    'QX80',
    'F-Pace',
    'Grand Cherokee',
    'Sportage',
    'Stinger',
    'GS 350',
    'Navigator',
    'Levante',
    'CX-5',
    '6 Dynamique',
    'C300 AMG',
    'Citan',
    'Lancer',
    'Touring',
    'Astra Sport',
    'Vivaro',
    '508 Allure',
    'Boxer PRO',
    '911 Carrera',
    'Grand Scenic',
    'Octavia RS',
    'BRZ Sport',
    'SX4 S-Cross',
    'Camry',
    'Corolla',
    'Sequoia',
    'Crafter',
    'Polo',
    'S60',
    'XC90',
    'Vesta SW',
    'XRAY',
    'Granta',
];

export default modelCollection;
